# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Mahdiar Farzinfar

###############################################################################
# GitHub Actions OIDC Federation — Basic Example
#
# Creates:
#   - The account-level GitHub Actions OIDC provider, or reuses an existing one
#   - One IAM role trusted by an exact GitHub environment subject
#
# The role intentionally receives no AWS permissions. Add only the
# least-privilege managed or inline policies required by your workflow.
#
# Before applying:
#   1. Configure protection rules on the target GitHub environment.
#   2. Obtain the repository's exact OIDC subject prefix from GitHub.
#   3. Supply it through a tfvars file or -var:
#
#      terraform init
#      terraform plan \
#        -var='github_repository_subject_prefix=repo:ORG@ORG-ID/REPO@REPO-ID'
#
# Existing repositories that still use name-based subjects can instead supply:
#   repo:ORG/REPOSITORY
#
# If the AWS account already has GitHub's OIDC provider, set
# create_oidc_provider=false and provide existing_oidc_provider_arn.
###############################################################################

terraform {
  # Root examples constrain known major versions and should commit the lock
  # file generated by terraform init.
  required_version = ">= 1.6.0, < 2.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.81.0, < 7.0.0"
    }
  }
}

# -----------------------------------------------------------------------------
# Inputs
# -----------------------------------------------------------------------------
variable "region" {
  description = "AWS region used to configure the provider. IAM resources are account-global."
  type        = string
  default     = "us-east-1"
  nullable    = false
}

variable "name_prefix" {
  description = "Prefix used to construct the example IAM role name."
  type        = string
  default     = "acme-platform"
  nullable    = false

  validation {
    condition     = can(regex("^[A-Za-z0-9_+=,.@-]{1,50}$", var.name_prefix))
    error_message = "name_prefix must be 1-50 characters and contain only supported IAM role-name characters."
  }
}

variable "github_repository_subject_prefix" {
  description = "Exact GitHub OIDC repository subject prefix, without a trailing context; for example repo:ORG@ORG-ID/REPO@REPO-ID or repo:ORG/REPOSITORY."
  type        = string
  nullable    = false

  validation {
    condition = can(regex(
      "^repo:[^:/?*\\s]+/[^:/?*\\s]+$",
      var.github_repository_subject_prefix,
    ))
    error_message = "github_repository_subject_prefix must match repo:<exact-owner>/<exact-repository> and must not contain whitespace or wildcards."
  }
}

variable "github_environment" {
  description = "Protected GitHub environment allowed to assume the deployment role."
  type        = string
  default     = "production"
  nullable    = false

  validation {
    condition     = can(regex("^[A-Za-z0-9_.-]{1,255}$", var.github_environment))
    error_message = "github_environment must be 1-255 characters using letters, numbers, dots, underscores, or hyphens."
  }
}

variable "create_oidc_provider" {
  description = "Whether this example should create the account-level GitHub Actions OIDC provider."
  type        = bool
  default     = true
  nullable    = false
}

variable "existing_oidc_provider_arn" {
  description = "ARN of an existing GitHub Actions OIDC provider; required when create_oidc_provider is false."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = (
      var.existing_oidc_provider_arn == null ||
      can(regex(
        "^arn:[a-z0-9-]+:iam::[0-9]{12}:oidc-provider/token\\.actions\\.githubusercontent\\.com$",
        var.existing_oidc_provider_arn,
      ))
    )
    error_message = "existing_oidc_provider_arn must be null or the ARN of GitHub's OIDC provider in an AWS account."
  }
}

# -----------------------------------------------------------------------------
# Derived values
# -----------------------------------------------------------------------------
locals {
  deployment_role_name = "${var.name_prefix}-github-deploy"
  deployment_subject   = "${var.github_repository_subject_prefix}:environment:${var.github_environment}"
}

# -----------------------------------------------------------------------------
# AWS provider
# -----------------------------------------------------------------------------
provider "aws" {
  region = var.region

  default_tags {
    tags = {
      ManagedBy = "terraform"
      Example   = "github-oidc-basic"
    }
  }
}

# -----------------------------------------------------------------------------
# GitHub Actions OIDC federation
# -----------------------------------------------------------------------------
module "github_oidc" {
  source = "../.."

  create_oidc_provider = var.create_oidc_provider
  oidc_provider_arn = (
    var.create_oidc_provider
    ? null
    : var.existing_oidc_provider_arn
  )

  audiences = ["sts.amazonaws.com"]
  role_path = "/github-actions/"

  tags = {
    Owner       = "platform-team"
    Environment = var.github_environment
  }

  roles = {
    deploy = {
      name                 = local.deployment_role_name
      description          = "Assumed by the protected GitHub environment ${var.github_environment}."
      subjects             = [local.deployment_subject]
      max_session_duration = 3600

      # Intentionally empty: add only workload-specific least privilege.
      managed_policy_arns = []
      inline_policies     = {}

      tags = {
        Purpose = "github-actions-deployment"
      }
    }
  }
}

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
output "deployment_role_arn" {
  description = "IAM role ARN to use as role-to-assume in aws-actions/configure-aws-credentials."
  value       = module.github_oidc.role_arns["deploy"]
}

output "oidc_provider_arn" {
  description = "ARN of the created or reused GitHub Actions OIDC provider."
  value       = module.github_oidc.oidc_provider_arn
}

output "trusted_subject" {
  description = "Exact GitHub OIDC subject trusted by the deployment role."
  value       = local.deployment_subject
}
